In [1]:
#qn 1
import numpy as np
arr=np.random.rand(4,2)
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.itemsize)

[[0.97430349 0.68325085]
 [0.77909898 0.17429521]
 [0.68414348 0.02867409]
 [0.92928811 0.86703793]]
(4, 2)
2
8


In [16]:
#qn2
import numpy as np
ar=np.arange(100,200,10)
ar

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190])

In [5]:
ar.reshape(5,2)

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

In [17]:
#qn3
import numpy as np
in_arr=np.array([[11,22,33], [44,55,66], [77,88,99]])
in_arr[0:,1]

array([22, 55, 88])

In [18]:
#qn4
a=np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
a[0::2,1::2]

array([[ 6, 12],
       [30, 36],
       [54, 60]])

In [20]:
#qn5
arr1=np.array([[5, 6, 9], [21 ,18, 27]])
arr2=np.array([[15 ,33, 24], [4 ,7, 1]])
s=arr1+arr2
print(s)
p=np.sqrt(s)
print(p)

[[20 39 33]
 [25 25 28]]
[[4.47213595 6.244998   5.74456265]
 [5.         5.         5.29150262]]


In [21]:
#qn6
arr = np.array([[34,43,73],[82,22,12],[53,94,66]])
print(arr)
print(arr[:,arr[1,:].argsort()])
print(arr[arr[:,1].argsort()])

[[34 43 73]
 [82 22 12]
 [53 94 66]]
[[73 43 34]
 [12 22 82]
 [66 94 53]]
[[82 22 12]
 [34 43 73]
 [53 94 66]]


In [5]:
import pandas as pd

In [12]:

info=pd.read_csv("C:\\Users\\HP\\Downloads\\Automobile_data (3).csv")

In [13]:
info


index      company   body-style  wheel-base  length engine-type  \
0       0  alfa-romero  convertible        88.6   168.8        dohc   
1       1  alfa-romero  convertible        88.6   168.8        dohc   
2       2  alfa-romero    hatchback        94.5   171.2        ohcv   
3       3         audi        sedan        99.8   176.6         ohc   
4       4         audi        sedan        99.4   176.6         ohc   
..    ...          ...          ...         ...     ...         ...   
56     81   volkswagen        sedan        97.3   171.7         ohc   
57     82   volkswagen        sedan        97.3   171.7         ohc   
58     86   volkswagen        sedan        97.3   171.7         ohc   
59     87        volvo        sedan       104.3   188.8         ohc   
60     88        volvo        wagon       104.3   188.8         ohc   

   num-of-cylinders  horsepower  average-mileage    price  
0              four         111               21  13495.0  
1              four         111               21  16500.0  
2               six         154               19  16500.0  
3              four         102               24  13950.0  
4              five         115               18  17450.0  
..              ...         ...              ...      ...  
56             four          85               27   7975.0  
57             four          52               37   7995.0  
58             four         100               26   9995.0  
59             four         114               23  12940.0  
60             four         114               23  13415.0  

[61 rows x 10 columns]

In [14]:
#qn 6
info[info["price"]==info["price"].max()][["company","price"]]

company    price
35  mercedes-benz  45400.0

In [16]:
#qn7
data = info.groupby("company")
data = data["company","price"].max()
data

company    price
company                              
alfa-romero      alfa-romero  16500.0
audi                    audi  18920.0
bmw                      bmw  41315.0
chevrolet          chevrolet   6575.0
dodge                  dodge   6377.0
honda                  honda  12945.0
isuzu                  isuzu   6785.0
jaguar                jaguar  36000.0
mazda                  mazda  18344.0
mercedes-benz  mercedes-benz  45400.0
mitsubishi        mitsubishi   8189.0
nissan                nissan  13499.0
porsche              porsche  37028.0
toyota                toyota  15750.0
volkswagen        volkswagen   9995.0
volvo                  volvo  13415.0

In [17]:
#qn8
GermanCars = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845, 171995, 135925 , 71400]} 
JapaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 'Price': [29995, 23600, 61500 , 58900]}
a1= pd.DataFrame.from_dict(GermanCars)
a2=pd.DataFrame.from_dict(JapaneseCars)
a=pd.concat([a1,a2],keys=["German cars","Japanese cars"])

In [18]:
a

Company   Price
German cars   0         Ford   23845
              1     Mercedes  171995
              2          BMV  135925
              3         Audi   71400
Japanese cars 0       Toyota   29995
              1        Honda   23600
              2       Nissan   61500
              3  Mitsubishi    58900

In [19]:
#qn 9
b=info.sort_values(by="price")

In [20]:
b

index        company body-style  wheel-base  length engine-type  \
13     16      chevrolet  hatchback        88.4   141.1           l   
27     36          mazda  hatchback        93.1   159.1         ohc   
48     66         toyota  hatchback        95.7   158.7         ohc   
36     49     mitsubishi  hatchback        93.7   157.3         ohc   
28     37          mazda  hatchback        93.1   159.1         ohc   
..    ...            ...        ...         ...     ...         ...   
11     14            bmw      sedan       103.5   193.8         ohc   
35     47  mercedes-benz    hardtop       112.0   199.2        ohcv   
22     31          isuzu      sedan        94.5   155.9         ohc   
23     32          isuzu      sedan        94.5   155.9         ohc   
47     63        porsche  hatchback        98.4   175.7       dohcv   

   num-of-cylinders  horsepower  average-mileage    price  
13            three          48               47   5151.0  
27             four          68               30   5195.0  
48             four          62               35   5348.0  
36             four          68               37   5389.0  
28             four          68               31   6095.0  
..              ...         ...              ...      ...  
11              six         182               16  41315.0  
35            eight         184               14  45400.0  
22             four          70               38      NaN  
23             four          70               38      NaN  
47            eight         288               17      NaN  

[61 rows x 10 columns]

In [21]:
#qn10
info["company"].value_counts()

toyota           7
bmw              6
mazda            5
nissan           5
volkswagen       4
mercedes-benz    4
audi             4
mitsubishi       4
alfa-romero      3
honda            3
porsche          3
jaguar           3
chevrolet        3
isuzu            3
dodge            2
volvo            2
Name: company, dtype: int64